language: elixir

elixir:
  - '1.14.2'
otp_release:
  - '25.1.2'

install:
 - sudo apt-get install clamav clamav-daemon
 - sudo freshclam
 - sudo clamd&

before_script:
 - mix local.hex --force
 - mix deps.get

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
